DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS MENU;

CREATE TABLE STOCK (
	ID		  			BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME		  		VARCHAR(50) NOT NULL,
	BARCODE	  			VARCHAR(200) NOT NULL,
	AMOUNT 				BIGINT NOT NULL
);

CREATE TABLE MENU (
	ID		  			BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME		  		VARCHAR(50) NOT NULL,
	TYPE_NAME	  		VARCHAR(20) NOT NULL,
	SUMMARY	  			VARCHAR(500) NOT NULL,
	AMOUNT	  			BIGINT NOT NULL
);

INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식1','FOOD','음식입니다1',1);
INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식2','FOOD','음식입니다2',1);
INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식3','FOOD','음식입니다3',1);
INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식4','FOOD','음식입니다4',1);
INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식5','FOOD','음식입니다5',1);
INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식6','FOOD','음식입니다6',1);
INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식7','FOOD','음식입니다7',1);
INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식8','FOOD','음식입니다8',1);
INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식9','FOOD','음식입니다9',1);
INSERT INTO MENU (NAME,TYPE_NAME,SUMMARY, AMOUNT) VALUES ('음식10','FOOD','음식입니다10',1);